apiVersion: spaces.upbound.io/v1alpha1
kind: SharedSecretStore
metadata:
  name: aws-secretsmanager-prod
  namespace: consumer-services
  labels:
    acmeco/team: consumer-services
    acmeco/environment: prod
spec:
  controlPlaneSelector:
    labelSelectors:
      - matchLabels:
          acmeco/environment: prod
  namespaceSelector:
    names:
      - default
  provider:
    aws:
      service: SecretsManager
      region: us-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-access-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-access-secret
            key: secret-access-key