apiVersion: spaces.upbound.io/v1alpha1
kind: SharedExternalSecret
metadata:
  name: providerconfig-creds-prod
  namespace: consumer-services
  labels:
    acmeco/team: consumer-services
    acmeco/environment: prod
spec:
  controlPlaneSelector:
    labelSelectors:
      - matchLabels:
          acmeco/environment: prod
  namespaceSelector:
    names:
      - default
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager-prod
      kind: ClusterSecretStore
    target:
      name: providerconfig-creds-prod
    data:
    - secretKey: creds
      remoteRef:
        key: secret-access-key